### ISSUE TITLE
InvalidMethodSignatureException in CitrusLifecycleHooks in citrus-cucumber Module

### ISSUE THREAD

**Issue by schaeferviada** [citrusframework/citrus#1047]
**Citrus Version**
The issue affects every Version since Version 3.0.0
3.x.x & 4.x.x

**Expected behavior**
The Class CitrusLifecycleHooks of the citrus-cucumber module uses the cucumber Hooks Before and After to add some additional information during the cucumber scenario test.
The citrus-cucumber module will be used to enable Citrus Annotions in Cucumber tests.

**Actual behavior**
The Cucumber tests can not be started, because of a InvalidMethodSignatureException in CitrusLifecycleHooks.
The Mehtods has a org.citrusframework.cucumber.backend.Scenario as parameter, but the Cucumber tests expect io.cucumber.java.Scenario scenario as parameter.
Because of this, the citrus-cucumber module can not be used.

```
Before All/After All failed
io.cucumber.core.exception.CompositeCucumberException: There were 2 exceptions. The details are in the stacktrace below.
	at io.cucumber.core.runtime.RethrowingThrowableCollector.getThrowable(RethrowingThrowableCollector.java:57)
	at io.cucumber.core.runtime.CucumberExecutionContext.getThrowable(CucumberExecutionContext.java:102)
	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:97)
	at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:85)
	at io.cucumber.core.cli.Main.run(Main.java:87)
	at io.cucumber.core.cli.Main.main(Main.java:30)
	Suppressed: io.cucumber.java.InvalidMethodSignatureException: A method annotated with Before, After, BeforeStep or AfterStep must have one of these signatures:
 * public void before_or_after(io.cucumber.java.Scenario scenario)
 * public void before_or_after()
at com.consol.citrus.cucumber.CitrusLifecycleHooks.before(com.consol.citrus.cucumber.backend.Scenario)
```

**Test case sample**
The citrus-samples for citrus-cucmber can be used for testing: [citrus-samples: citrus-cucumber ](https://github.com/citrusframework/citrus-samples/tree/main/samples-cucumber/sample-cucumber)

**Comment by christophd** [comment]
I am afraid I am not able to reproduce this error on my side.

I have also checked the citrus-samples:citrus-cucumber sample project and this runs fine on my side and also on GitHub actions CI workflow.

I guess you are failing to enable the Citrus Cucumber backend and its object factory because this is what makes this working. You may double check the settings in `cucumber.properties` to load the Citrus object factory (see [sample-cucumber/src/test/resources/cucumber.properties](https://github.com/citrusframework/citrus-samples/blob/main/samples-cucumber/sample-cucumber/src/test/resources/cucumber.properties))

**Comment by christophd** [comment]
Please try to run the Java class (in `src/test/java`) from your IDE instead of running the feature file directly. The Java class is doing some more configuration that is required

**Comment by christophd** [comment]
May be related to #1116
