### ISSUE TITLE
Questions about JMS regarding headers

### ISSUE THREAD

**Issue by npapageorgopoulos** [citrusframework/citrus#1194]
**Citrus Version**
4.1.0

**Question**
1. How do add a subject to a JMS message?
Is something like  `.header("Subject", "ExampleSubject")`  while sending the message?

2. Is a custom property an addition to the header as well?
Similar as the previous question ` .header("customProperty", "customValue")` ?

3. Does the `receive` action work as a Consumer for topics as well?
Are there any specific configurations for this, because all I can think of is that it is manually triggering the receiving messages.

4. Is there Quarkus support for JMS in Citrus
Browsing on the Samples I found for Kafka and other examples, I created a project and in order for a JmsEndpoint with `@CitrusEndpoint`  Annotation to work, it required `@Bean` of Spring Context and `citrus.spring.java.config` as well.

**Comment by bbortt** [comment]
hello @npapageorgopoulos and sorry for the long delay.. if kinda lost track of this issue. anyways. hope it's not too late.

> How do add a subject to a JMS message?

there are numerous samples doing this; e.g.: https://github.com/citrusframework/citrus/blob/main/endpoints/citrus-jms/src/test/java/org/citrusframework/jms/integration/SyncJmsTopicJavaIT.java

> Is a custom property an addition to the header as well?

yes, of course. as you can see in the sample linked above, _any_ string value can be applied to headers. we often use "operation" and "correlationId" because they seem like a good fit in the samples, but it's not mandatory.

> Does the receive action work as a Consumer for topics as well?

yes, see also the linked sample. messages are being sent as well as received! some actions work as a producer, some as a consumer/responder. all that is possible through the use of asynchronous/parallel actions.

> Is there Quarkus support for JMS in Citrus

I _think_ not from looking at the [`citrus-jms/pom.xml`](https://github.com/citrusframework/citrus/blob/main/endpoints/citrus-jms/pom.xml). it includes dependencies to spring. but I am not entirely sure, @christophd could give you more hints here for sure.
