### ISSUE TITLE
ci: Build hanging due to endless loop in Kafka tests

### ISSUE THREAD

**Issue by christophd** [citrusframework/citrus#1258]
**Citrus Version**
latest

**Description**
The GitHub actions workflow is running into endless loop while verifying as part of the Kafka tests. I think this is due to running tests in parallel and recently I have introduced Testcontainers module that also start some Kafka tests. Need to investigate.

Asa first step we should find a proper loop ending condition on the tests to avoid the build running forever.

Examples:
https://github.com/citrusframework/citrus/actions/runs/11710427055
https://github.com/citrusframework/citrus/actions/runs/11710751209

**Comment by bbortt** [comment]
@christophd I've started working on this a week ago already! my idea was to introduce a timeout to the "try until condition" (respectively the base class of these loop-action-types). I think that would be a nice feature anyway. because, as you can see, if the condition isn't met; it just loops forever.

I have the implementation ready, just need to transfer it into the base class. didn't find time since last week, but would sure be able to complete it on saturday.

**Comment by christophd** [comment]
that sounds awesome! many thanks and take your time

**Comment by christophd** [comment]
@bbortt I think we can close this one fixed, right?

**Comment by bbortt** [comment]
I think so. didn't see it anymore.
