### ISSUE TITLE
Switching between environments eng. Dev, TEST

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#382]
@vmasule asked in https://github.com/christophd/citrus-samples/issues/25:

I am new to citrus and currently evaluating it's suitability for our project. I have created a sample project but I got stuck how I can switch between different environments like Spring-Boot has spring profiles. Is there any example of it switching between environment?

**Comment by FMAOuroboros** [comment]
Hi @vmasule!

Basically citrus is an integration test framework. So in general one wouldn't execute integration tests in the same stage as you would execute unit test, because for Citrus, a deployed piece of software is required. In addition in general one wouldn't execute exact the same integration tests on the same artifact, assuming that you ship an immutable artifact.
Maybe you could share some more details about your use case?

Nevertheless, you could set system variables depending on the environment you're in as you would do in docker container. 

Maybe there is a possibility to reuse spring profiles with citrus, but this is something @christophd can tell you for sure.

BR,
Sven

**Comment by svettwer** [comment]
Closed due to no response.
