### ISSUE TITLE
Customize XML parser doesn't work

### ISSUE THREAD

**Issue by chokdee** [citrusframework/citrus#425]
I have tried as it described in chapter 10.2.1
But unfortunately it doesn’t work. I think the reason is that the Instance is created with new in XMLUtils instead of using a spring bean

**Comment by svettwer** [comment]
Hi!

Sorry, but I can't reconstruct your issue. 
`private static XmlConfigurer configurer = new XmlConfigurer();` in `XMLUtils` is not an issue, because `XmlConfigurer implements InitializingBean` and takes care of it's initialization within `XMLUtils`.

Would it be possible for you to provide an example on this?

BR,
Sven

**Comment by svettwer** [comment]
I'll remove this issue from the 2.7.8. milestone, because it's currently not solvable without more information.

BR,
Sven

**Comment by svettwer** [comment]
Closed because of inactivity
