### ISSUE TITLE
Customize Metadata

### ISSUE THREAD

**Issue by chokdee** [citrusframework/citrus#431]
Hello,
I follow the chapter 46 and add our necessary meta data to the xml. 
Now my first question. I do not find any of the customized property inside any outputfile. How shall I grap this information if I want to customize the report?

Then I follow your hint to use better Java DSL. But I don not see any method to add custom properties to the MetaInfo. It this implemented? 
Or do I missunderstand you idea?

**Comment by christophd** [comment]
Custom meta information is currently not parsed to the object test case representation. It has been used by custom reporting mechanism that parsed the XML fields in order to add those to the customized report.

This is a subject to change. We should provide the custom information to the meta info value object on the test case. Then custom reporters can read and evaluate the custom information more easily. Also we should provide a way to set custom meta information fields in Java DSL.

**Comment by svettwer** [comment]
@christophd I think it would be a good idea to close this issue in favor of a feature request. What do you think?

**Comment by svettwer** [comment]
Hi!

I'm currently reviewing the open issues. As we're deprecating the XML-DSL, we'll not add those meta information to the reports. Providing meta information in the JAVA-DSL would be a completely other topic and more a feature than an enhancement. So my question is, how important are the meta information for you? :thinking: 

BR,
Sven

**Comment by chokdee** [comment]
I don't need it anymore.
But is it a joke to deprecated the XML DSL?
Do you write a converter for this? We have 2000 testcases written in XML

**Comment by svettwer** [comment]
Hi!

>I don't need it anymore.

Okay, thank you. I'll close this issue then.

>But is it a joke to deprecated the XML DSL?

As stated in the [Roadmap blogpost for 2019](http://citrusframework.org/news/2019/01/17/citrus-roadmap-2019/):
*In order to improve the maintainability of the framework and reduce the complexity from a user’s perspective, we are going to deprecate the XML-DSL. The use case for the XML-DSL was to provide a way to create integration tests without any knowledge of Java. As we are moving to a DevOps world and software developers become testers as well, the use case for the XML-DSL gets more and more obsolete. The deprecation should encourage users to start developing their tests in Java and migrate their current XML-DSL test suites. It will be some time before the XML-DSL is completely removed from the framework but going forward the focus is clearly on the Java DSL. We will announce the final removal with a lead time of at least one year to give users enough time for migration. Until then, the XML-DSL will still be usable as it is but it will not be extended or supported as part of the open source project.*

>Do you write a converter for this? 

This would be possible from a technical perspective and we already thought about that. The converter will be complex as there is a lot of XML-DSL to convert. Maybe there are some people in the community to support us with this. In any case, there will be a solution, when it's time.

BR,
Sven
