### ISSUE TITLE
Unable to click on a button element in a hidden form

### ISSUE THREAD

**Issue by SajanaKrishnan** [citrusframework/citrus#465]
**Citrus Version**
Citrus 2.7.6

**Question**
Is there a way Citrus can help with clicking on a button element on a hidden form?

**What I've tried so far**
I tried getting webdriver instance and using javascript executor
JavascriptExecutor Executor = (JavascriptExecutor) browser.getWebDriver();
Executor.executeScript("arguments[0].click();", btnAddNewCard);

**Additional information**
1. The driver instance returns null when I cast it from browser - Webdriver driver = (WebDriver) browser;

**Comment by svettwer** [comment]
Hi!

I assume that you're using the `TestDesigner`, right?
In this case design time differs from text execution time. Therefore you'll receive a `null` value here.

```java
public class foobar extends TestNGCitrusTestRunner {

    @Autowired
    private SeleniumBrowser browser;

    @Test
    @CitrusTest
    public void testIndexPage() {

        selenium(action -> action
                .browser(browser)
                .start());

        JavascriptExecutor Executor = (JavascriptExecutor) browser.getWebDriver();
        echo("foo");
    }
}
```

Try this snippet and add a break point at the `echo` action. You'll see that the executor is set correctly. This is because I'm using `TestNGCitrusTestRunner` instead of `TestNGCitrusTestDesigner`.

In case that you've implemented a lot of Designer tests you don't want to migrate to a Runner, I recommend to use the `TestNGCitrusTest` interface. With this interface, you're able to switch between designer and runner on test basis.

```java
@Test
public class InjectionTest extends TestNGCitrusTest {

    @CitrusTest(name = "JUnit4DesignerTest")
    public void designerTest(@CitrusResource TestDesigner designer) {
        designer.echo("Now working on designer instance");
    }

    @CitrusTest(name = "JUnit4RunnerTest")
    public void runnerTest(@CitrusResource TestRunner runner) {
        runner.echo("Now working on runner instance");
    }
}
```
For more information concerning this topic, please have a look at the documentation concerning [test-resource-injection](http://citrusframework.org/citrus/reference/html/index.html#test-resource-injection).

BR,
Sven

**Comment by SajanaKrishnan** [comment]
Thanks Sven. Let me check and get back.

**Comment by SajanaKrishnan** [comment]
Thanks. It worked
