### ISSUE TITLE
browser, soap instance is null when used in different classes, in different maven packages

### ISSUE THREAD

**Issue by SajanaKrishnan** [citrusframework/citrus#472]
**Citrus Version**
2.7.6

**Question**
My framework hierarchy is as follows
1. com.org.utils package has 
             EndPointConfig.java - bean config of SeleniumBrowser, WebServiceClient soap
            GlobalVariables.java, 
            TestDataAdapter.java - connecting to excel data sheet
2. com.org.web.tests
              webtests.java - able to get the browser instance and working fine
3. com.org.web.page
             profilepage.java - selenium(action -> action.browser(browser).select(newChallengeQuestion).element(By.name("Questions[0].QuestionId"))); throws null pointer exception 
4. com.org.api
         getPromocode.java - variable("clientId", clientIdValue);- throws null pointer exception
                 soap(action -> action.client(todoClient()).send().fork(true)
				.soapAction("http://tempuri.org/PCService_Def/GetPromocode")
				.payload(new ClassPathResource("APITemplates/getPromocodeRequest.xml"))); - throws null pointer exception

**What I've tried so far**
	@Autowired(required = true)   in ProfilePage.java
	public SeleniumBrowser browser;
           @Autowired(required = true)   in GetPromocode.java
	public WebServiceClient soapClient;

**Additional information**
Please help overcome this scenario. My framework requires multiple packages and multiple classes that needs to access the current instance of the bean config objects.
 In my case, SeleniumBrowser, SoapClient, HTTP, FTP

**Comment by svettwer** [comment]
Hi!

I think this is not an issue of the citrus framework but with your project setup. If your autowiring doesn't work, I recommend to check the spring documentation for further information. I also recommend the [citrus-samples](https://github.com/citrusframework/citrus-samples) with working examples of most of the citrus features.

We're unable to provide free analysis and support on user projects but we also offer enterprise support where we help you to overcome your issues in your concrete project.
If you're interested, please get in touch with us via https://www.consol.com/contact/

BR,
Sven

**Comment by SajanaKrishnan** [comment]
Hi Sven,

I spoke with Simon and Nico from your team. Simon mentioned, he will get back about browser instance being null even after autowiring in page objects. Can you please help me. I have gone over most of the citrus samples to find a solution. 
This is critical for me to choose between citrus and other frameworks

Regards,
Sajana

**Comment by svettwer** [comment]
Hi!

I would really love to help you, but I'm not able to analyze null pointer exceptions based on code snippets. There are a few candidates based on the information you've provided but this isn't even a complete class. So I've no information about further members of the class. I've also no information about your configuration as well.

So please formulate a concrete question for a use case without implementation details, so that we're able to provide a solution attempt. 
E.g. I've a service for user registration and I would like to create a new user over the frontend and verify that a jms event is produced to announce the new user in the system.

With such a question, I could easily write down a snippet you'd just have to adapt to your scenario. But I can't help with implementation details and nullpointer exceptions based on snippets posted in GitHub issue.

BR,
Sven

**Comment by christophd** [comment]
For autowiring to be enabled your page object needs to be part of the Spring application context (as a Spring bean). In addition to that you need to instantiate the page object via the application context. Otherwise Spring`s autowire mechanism is not performed and your object is null.

Can you point out how your page object is instantiated at the moment? Is it part of the application context as Spring bean definition?

**Comment by SajanaKrishnan** [comment]
Hi,

I instantiate my page object class by creating an object in the test method.

For Ex: I have DriverTests.java that calls methods from pageobjects LoginPage, ProfilePage.java
All my classes extend TestNGCitrusTestRunner

In the DriverTests.java, in test method test() I am creating an object for LoginPage loginPage = new LoginPage(); then using selenium(action -> action.browser(browser).page(loginPage).execute("cardLogin"));
If I need to getWebdriver in cardLogin method, it is always  null 

If you suggest a different approach, pls give me examples.

Regards,
Sajana

**Comment by christophd** [comment]
the problem is the `LoginPage loginPage = new LoginPage()` if you instantiate the page object on your own with `new` the Spring application context is not applying the autowire mechanism. This is why your object results to be null.

Please add the LoginPage to the Spring application context as Spring bean and retrieve that page from the application context. That is the only way to have dependency injection with autowiring enabled in your page object.

This mechanism is briefly described in the Spring framework documentation. So I recommend to also consult the Spring concepts.

General usage of Selenium with Citrus in combination with page objects is shown here: https://github.com/citrusframework/citrus-samples/tree/master/sample-selenium/java-dsl

Please follow this sample and the Spring documentation.

**Comment by christophd** [comment]
The Citrus documentation also gives some information on what is possible with page objects in Citrus:

http://citrusframework.org/citrus/reference/html/index.html#page-actions
http://citrusframework.org/citrus/reference/html/index.html#page-validation

**Comment by SajanaKrishnan** [comment]
Hi Chris,

I see null pointer exception when calling a method that has variable(name,
value) and soap(action -> action.)
Looks like TestRunner methods variable and TestAction soap(configurer) are
not passing value.

I tried printing the available beans and their hashcode in the method and
it prints them all.

Can you pls help


Regards,
Sajana

**Comment by SajanaKrishnan** [comment]
Can you pls help me with this.

I am briefing a bit more..

I have a method 1 [@Test @CitrusTest] in a different package that calls a
method 2 from a different package.

Method 2 has variable(name, value) and soap(action -> action...)

I instantiated bean- bean2 for method 2 and autowired it in method 1. Then
called from method 1 as bean2.method2();

The runner.variable and runner.soap(configurer) throw null pointer exception


Regards,
Sajana

**Comment by svettwer** [comment]
Hi!
Just recognized that you're posting on a closed issue. This is hard to manage for us and may get out of scope.
Please open a new issue for further questions. 

BR, 
Sven
