### ISSUE TITLE
Selenium Screenshot not working in Page Objects

### ISSUE THREAD

**Issue by SajanaKrishnan** [citrusframework/citrus#493]
**Citrus Version**
2.7.6

**Question**
I have a Page Object (LoginPage) in a different package, than the test class. LoginPage is a Spring Bean and autowired in the test class.
selenium(action -> action.browser(browser).screenshot("test-output/Screenshots")); in LoginPage throws Null Pointer Exception at 
public TestAction selenium(BuilderSupport<SeleniumActionBuilder> configurer) {
        **return testRunner.selenium(configurer);**
    }

**What I've tried so far**
Tried to see if browser.getWebDriver() has any methods to take screenshot from LoginPage.
Also, tried selenium(builder -> builder.browser(browser).screenshot("test-output/Screenshots"))
No LUCK!

**Additional information**

**Comment by svettwer** [comment]
Hi!

I've tested the screenshot feature as specified by your snippet and it works fine.
```java
    @Test
    @CitrusTest
    public void testIndexPage() {
        selenium(selenium -> selenium
                .browser(browser)
                .start());

        selenium(selenium -> selenium.navigate(todoClient.getEndpointConfiguration().getRequestUrl()));

        selenium(selenium -> selenium.find()
                        .enabled(true)
                        .displayed(true)
                        .element(By.linkText("Run application")));

        selenium(selenium -> selenium.click()
                        .element(By.linkText("Run application")));

        selenium(selenium -> selenium.find()
                .element(By.tagName("h1"))
                .text("TODO list"));

        selenium(selenium -> selenium
                .browser(browser)
                .screenshot("test-output/screenshots"));
    }
```

Currently, it's hard to say where the null pointer comes from but it seems that you've an issue with your project setup. I recommend you to have a detailed look at the samples in the [citrus-samples](https://github.com/citrusframework/citrus-samples) repository especially the samples concerning selenium. The samples contain a working project setup. From there you can easily start to work yourself through the differences between the sample project and your test project. I'd also like to highlight the introducing chapters of the [citrus documentation](http://citrusframework.org/citrus/reference/html/index.html) where there is also a explanation how all the bits and pieces come together. 

BR,
Sven

**Comment by SajanaKrishnan** [comment]
Hi Sven,

The screenshot function written in test class works just fine. But when I
write it in a page object it does not.

Ex: @Test @CitrusTest

public void testIndexPage() {
        selenium(selenium -> selenium
                .browser(browser)
                .start());

        selenium(selenium ->
selenium.navigate(todoClient.getEndpointConfiguration().getRequestUrl()));

        selenium(selenium -> selenium.find()
                        .enabled(true)
                        .displayed(true)
                        .element(By.linkText("Run application")));

        selenium(selenium -> selenium.click()
                        .element(By.linkText("Run application")));

        selenium(selenium -> selenium.find()
                .element(By.tagName("h1"))
                .text("TODO list"));

        selenium(selenium -> selenium
                .browser(browser)
                .screenshot("test-output/screenshots"));
    Selenium(action ->
action.browser(browser).page("loginPage").execute("login"));

}


It is just fine above!

Now in LoginPage Class - login method --

I call

selenium(action -> action
                .browser(browser)
                .screenshot("test-output/screenshots"));

It throws null pointer exception at testRunner.selenium(configurer)



Regards,
Sajana

**Comment by SajanaKrishnan** [comment]
Any luck with this?

**Comment by svettwer** [comment]
Hi!

I think I've got an idea of what you're trying to do.

```java
public class TodoPage implements WebPage, PageValidator<TodoPage> {

    @FindBy(tagName = "h1")
    private WebElement heading;

    @FindBy(tagName = "form")
    private WebElement newTodoForm;

    @FindBy(xpath = "(//li[@class='list-group-item'])[last()]")
    private WebElement lastEntry;

    /**
     * Submits new entry.
     * @param title
     * @param description
     */
    public void submit(String title, String description) {
        newTodoForm.findElement(By.id("title")).sendKeys(title);

        if (StringUtils.hasText(description)) {
            newTodoForm.findElement(By.id("description")).sendKeys(description);
        }

        newTodoForm.submit();
    }

    public void takeScreenshot(SeleniumBrowser browser){
        selenium(action -> action
                .browser(browser)
                .screenshot("test-output/screenshots"));
    }

    @Override
    public void validate(TodoPage webPage, SeleniumBrowser browser, TestContext context) {
        Assert.assertEquals(heading.getText(), "TODO list");
        Assert.assertEquals(lastEntry.getText(), "No todos found");
    }
}
```

If it is like the above, this doesn't work. It's not possible to use citrus actions in `WebPages`, because the whole citrus infrastructure is not present in this context. 
If you want to stay with this attempt, you'd have to reimplement the screenshot functionality using the selenium API as shown [here](https://stackoverflow.com/questions/13832322/how-to-capture-the-screenshot-of-a-specific-element-rather-than-entire-page-usin)

I would recommend to take the screenshot from the test case as a test step as designed in the citrus API.

BR,
Sven

**Comment by SajanaKrishnan** [comment]
Thanks Sven. This is exactly what I am trying to do. Not just screenshot
alone [runner.selenium()]. In my other classes and methods
runner.variable() and runner.soap() gives null pointer exception. Is there
a way I can manually inject my citrus infrastructure in the methods I am
calling from different classes and in different packages?

I am working in a multi team environment where the requirements are shared
and executed. I also tried talking to spring experts, they could not help
me as well.

You are my only hope to help me get this problem over!

Regards,
Sajana

**Comment by christophd** [comment]
You are about to mix Citrus test message flow logic with page objects which is not a good idea in my eyes. 

Why do you need to create variables or trigger SOAP requests from within the page object? The page object should only interact with the browser web driver in order to trigger some events or validate the state on the user interface.

After the page object has performed its user interface related action you can continue ti use the Citrus Java DSL in your normal test as usual. Why is that not working for you?

**Comment by svettwer** [comment]
Hi!
I was thinking a while about your scenario and hope to understand it correctly.

> I am dealing with multi team requests and
their execution scenarios are either on page object level or api or mixed.

Citrus is ideal for those mixed use cases.

>By this classification, I am trying not only to achieve multi team
execution requests but also multi team members to contribute test cases in
their packages.

So you've various packages for different teams testing different parts of the software like frontend or api? Every team has it's own distinct package to work in but the test should share some basic structures? Or is it like that the test steps may be mixed with each other?

>My test class can either be for api or page object or both depending on the
team and test type.

So you want to unify api and frontend test in one test workflow?

Generally spoken:
Whenever you want to extract some reusable citrus functionality, [Behaviors](http://citrusframework.org/citrus/reference/html/index.html#java-dsl-test-behaviors) are a good way to do so. With behaviors, you're able to parameterize and isolate functionality so that it is reusable for multiple teams (E.g. a screenshot functionality). This could also be used to unify some kind of a test workflow by specifying interfaces for various steps of the test workflow. I'd recommend to avoid bending Citrus to fit in your use case.

**Comment by SajanaKrishnan** [comment]
Please give me a few behavior example in my case like using the screenshot
and creating variable, soap action in reusables.

Thanks,
Sajana

**Comment by svettwer** [comment]
Hi!

Well, a good behavior implementation requires some design thoughts that are based on the project and the use case. Because I've no idea what your project is, I'm unable to provide a made-to-measure example. Nevertheless, I can provide some pattern and best practices that you can adapt to your requirements:

1. There are behavior examples in the [citrus-samples](https://github.com/citrusframework/citrus-samples) and a section about [test behaviors](http://citrusframework.org/citrus/reference/html/index.html#java-dsl-test-behaviors) in the documentation to get an idea of how they work and what they're used for.
2. Use constructors or setters to configure your behavior implementations depending on your use case.
3. Extract behaviors in dedicated classes extending `AbstractTestBehavior`.

BR,
Sven

**Comment by SajanaKrishnan** [comment]
Thanks Sven. What I meant to ask was -  If a page object needs to perform a
test action such as selenium (action ->
action.browser(browser).screenshot()), how do I write test behaviors?
What are the changes in my test class and in my page objects?

Let me explore about it from the link and steps below and see if I can get
it working.

Regards,
Sajana

**Comment by svettwer** [comment]
Hi!

>What I meant to ask was -  If a page object needs to perform a
test action such as selenium (action ->
action.browser(browser).screenshot()), how do I write test behaviors?

Citrus is not designed this way. You would not execute a behavior from a page object.
You would design a behavior accepting a page to perform the actions on.

```java
private class MyFancyBehavior extends AbstractTestBehavior {

        private final Page page;
        private final TestNGCitrusTestDesigner designer;

        public foobar(final Page page, final TestNGCitrusTestDesigner designer) {
            this.page = page;
            this.designer = designer;
        }

        @Override
        public void apply() {
           //do something with your page here.
        }
    }
```

BR,
Sven

**Comment by svettwer** [comment]
Hi!

This won't work, because `@Parameters` works only together with `@Test`. Nevertheless, this is not a Citrus related question and additionally off topic. There are ways to achieve this for sure and there might be more elegant ways for test configuration depending on the concrete use case, but we're unable to provide free consulting as part of this open source project.
In addition: Different questions deserve different issues. This makes it easy for us to keep track and helps the discussion to stay with the topic.

BR,
Sven

**Comment by svettwer** [comment]
Closed because of inactivity.
