### ISSUE TITLE
Pass TestNG parameters to Beans

### ISSUE THREAD

**Issue by SajanaKrishnan** [citrusframework/citrus#503]
**Citrus Version**
2.7.7

**Question**
I am looking for ways to pass TestNG.xml parameters as values into java dsl beans in endpointconfig.java

For Ex:   @Bean
    public HttpClient todoClient() {
        return CitrusEndpoints.http()
                            .client()
                            .requestUrl(requestUrl)
                            .build();
    }

The requestUrl must be supplied from testng.xml

**What I've tried so far**

**Additional information**

**Comment by svettwer** [comment]
Hi!

Sorry, this is not a question concerning Citrus but concerning Spring and TestNG. Please ask those questions in the respective communities as we're unable to provide support for technologies other than citrus as part of this open source project.

In this special situation @SajanaKrishnan:
We've helped you over the last months with great zeal and passion, even if some of your questions were not relevant to Citrus. We've provided snippets to you that were especially made for your use cases, we provided advice and recommendations to help you to solve the challenges you're facing in your project with various technologies beside citrus. We've had calls and video conferences to help you to the best of our knowledge and certain. We've done all this to help you, because we love open source and knowledge sharing. Over the last few weeks, there was a growing feeling that you use the passion and the helpfulness of this community to overcome the technical challenges of your project. This is why we will only answer Citrus specific questions from now on as part of this open source project. All other questions will be closed with a reference to this comment.
We're also able to help you to overcome challenges not coupled with Citrus, but we can't do this for free. To be able to provide Citrus to the community as an open source project, it's required that we make money someway as it's not possible to keep the pace high just with our spare time. So if you want to work with us to solve your problems in your project, please   contact us via the [ConSol contact form](https://www.consol.com/contact/). Please note that working with ConSol supports the Citrus development as ConSol is the major sponsor behind Citrus.
I hope you can understand our point.

BR,
Sven
