### ISSUE TITLE
setting numbers as string in JSON

### ISSUE THREAD

**Issue by elvinsp** [citrusframework/citrus#538]
**Citrus Version**
2.7.7

**Question**
It would like to manipulate a string in a json resource with the string "000111".
At the moment the leading zeros are cut off because <element/>

> 
>       <send endpoint="configRequestEndpoint">
>         <message type="json">
>           <resource file="file:src/test/templates/json/api/config/saveGroupTrips.json"/>
>           <element path="$.data.trips[*].sourceBits" value="000110"/>
>         </message>
>       </send>

interprets it as a number and inserts it as an integer into JSON, whereas my application is expecting a string in sourceBits.

As far as I look, it is not possible to decide as what the datatype of a number should be, is it?

**Comment by svettwer** [comment]
Hi!

Yes, this is correct. If the value is convertible into an Integer, it will be converted. 
Nevertheless, it would be possible to add a `datatype` attribute to the `element` tag to override the default behavior, so that the value would be interpreted as a `String` in your case.

Would you mind to open a feature request for this?

BR,
Sven
