### ISSUE TITLE
Breaking change in selenium().browser().type() public API

### ISSUE THREAD

**Issue by martinmaher** [citrusframework/citrus#551]
**Citrus Version**
    >= 2.7.2

**Description**
If you upgrade your Citrus version to 2.7.2 or higher, we've a breaking change in the selenium browser builder API. We'll correct this with one of the future releases to ensure effortless version upgrades

**API before change**
```java
CitrusEndpoints.selenium()
        .browser()
        .browserType(BrowserType.CHROME)
        .build();
```

**API after change**
```java
CitrusEndpoints.selenium()
        .browser()
        .type(BrowserType.CHROME)
        .build();
```

**Additional information**
* Issue:#228
* Commit: https://github.com/citrusframework/citrus/commit/18ed4a226cd96803cf959282a531496925dd2081

BR,
Martin

**Comment by svettwer** [comment]
Hi!

> What is the motivation in introducing a deprecated version of a method rename that has been done 5 releases prior to the actual release?

Because the method has not been annotated as `@Deprecated` but simply removed. This is a breaking change in a public API introduced in a minor release. Such breaking changes cause effort when performing minor version upgrades by Citrus users. We're currently trying to prevent such efforts by introducing removed API and deprecate them so that they can be removed in a major version Update completely. This gives the users time for a migration.

>Someone who is now at v2.7.1 would have to upgrade to v2.7.9 in order to get the "effortless" non breaking change.

Correct. Our intent is to provide a clean, downwards compatible API with 2.7.9 to have a point to migrate to, so that the users can leverage from prior bug fixes without migration efforts.

>I think the upgrade from v2.7.1 to v2.7.9 is not going to be effortless anyways because so much has been changed and updated in that span of releases.

Correct. There have been a lot of changes in the public API which we're currently identifying to make it easier to upgrade to future Citrus versions.

**Comment by christophd** [comment]
Improved change management and minor/major version upgrade policies are for sure a good point to improve for future releases. No doubt there. 

But I do not think that the changes that we are talking about here have caused anybody some trouble when upgrading. Neither those changes were preventing somebody from upgrading. I think the changes that we are talking about can be managed easily by users upgrading as they are very straight forward. Nobody really should be wasting more than one hour time to incorporate these changes into the project. 

I think the introduced duplication with deprecation is not appropriate in most of the cases.

**Comment by svettwer** [comment]
Hi!

We've had contact with users that were waiting for a bug fix in the newest version. As the version came out, they wanted to upgrade so that their tests could run. But instead of being able to just change the version number and that's it, they had to invest time, that was not planned, to fix public API changes. Even if it's just an hour, we've caused effort on the users side that was unpredictable for them and that would have been avoidable by adding `@Deprecated` annotations.

We just want to invest the time to increase the quality of the API, that's all. I don't think that this is inappropriate.

BR,
Sven

**Comment by christophd** [comment]
Just saying an upgrade from v2.7.1 to v2.7.9 will not be effortless even with the introduced deprecations. You will have to invest some time to adjust things that's a fact.

**Comment by christophd** [comment]
Ok I see I will not convince you. But you may neither make me believe that this particular change here will reduce any significant effort for anybody upgrading from v2.7.1 to v2.7.9.

**Comment by svettwer** [comment]
We've just to add some documentation here.
This can be done after #565 has been approved.

BR,
Sven

**Comment by svettwer** [comment]
Added missing documentation to PR #565.
