### ISSUE TITLE
TestContext variable within conditional()

### ISSUE THREAD

**Issue by eikeg** [citrusframework/citrus#625]
**Citrus Version**
2.8.0

**Expected behavior**
Variable visible in TestContext after creation also within action list of `conditional()`

**Actual behavior**
Variable is only visible as `${var}`, but not as `context.getVariable("var")`

**Test case sample**
> Please, share the test case (as small as possible) which shows the issue
```java
// works
conditional().when("1 = 1").actions(createVariable("foo1", "bar"), echo("${foo1}"));
// FAILS
conditional().when("1 = 1").actions(createVariable("foo2", "bar"), echo(context.getVariable("foo2")));
// works
conditional().when("1 = 1").actions(createVariable("foo3", "bar"));
echo(context.getVariable("foo3"));
// works
conditional().when("1 = 1").actions(createVariable("foo4", "bar"));
conditional().when("1 = 1").actions(echo(context.getVariable("foo4")));
```

**Comment by svettwer** [comment]
Hi!

I assume the complete test case is similar to the following:
```java
public class TodoListIT extends TestNGCitrusTestRunner {

    @Test
    @CitrusTest
    @Parameters("context")
    public void testGet(@Optional @CitrusResource TestContext context) {

        conditional().when("1 = 1").actions(
                createVariable("foo2", "bar"),
                echo(context.getVariable("foo2")));

    }

}
```

This test fails, because the variable has not set up yet at the point when you are requesting it from the context. During the setup of the test container, the actions to be executed are stored internally but not executed directly.

Let's have a look at the following:
- `createVariable("foo2", "bar")` is an `CreateVariablesAction` which is setup for an execution during the containers run time.
- `echo("Some String")` is an `EchoAction` which is also setup for an execution during the containers run time.

If you've some parameter evaluation to setup the test actions, these evaluations are done _before_ the container has been started. So in your case:

1. Setup `createVariable("foo2", "bar")` for later execution
2. Evaluate the parameter for the `EchoAction` from `context.getVariable("foo2")`
3. Setup `echo()` for later execution. 

The third step will not be executed, as the second step errors. The second step will error, because the first step hast not been executed yet.

I hope that makes it clearer how the framework works. Depending on your use case, you could try to wrap your context access into an `AbstractTestAction`to delay the execution to the container runtime.

BR,
Sven

**Comment by eikeg** [comment]
Hi,

ok, understood; I was assuming something like that, and I am now using an `AbstractTestAction` as workaround.

But from a user's point of view this is very confusing in Java DSL runner. Whereas in XML one can just "move" actions from main method into containers or templates, in Java runner main code, containers, and behaviors are all slightly different.

In my case I have two almost identical cases of `createVariable()` followed by `applyBehavior()`, and was wondering why one works, and the other one (inside `doFinally( ... conditional(...))`) failed...

Regards,
Eike

**Comment by svettwer** [comment]
Hi!

Good to hear the workaround works for you. In comparison to XML tests, which are declarative, Java tests, which are imperative, requires some more thoughts about the test setup especially if you start using advanced features like containers here. I agree, that there are a few rough edges that need to be smoothed out.

BR,
Sven
