### ISSUE TITLE
How to put wait after microservice API call for angular application

### ISSUE THREAD

**Issue by vmasule** [citrusframework/citrus#629]
**Citrus Version**
2.8.0

**Question**
How to put wait after microservice API call for angular application?

**What I've tried so far**

```
selenium().click().element(By.id("find-application"));
selenium().waitUntil().element(By.className("search-results")).visible();

```
and

```
selenium().click().element(By.id("find-application"));
selenium().browser(browser).waitUntil().element(By.className("search-results")).visible();
```

**Additional information**
I am using java DSL, website is built with angular 7, On click of search I get search result but above samples don't wait for result data which is dynamically loaded.

**Comment by vmasule** [comment]
@christophd @rhuss @marcelmay @sgbeal Any update on this please.

**Comment by sgbeal** [comment]
i'm not involved in Citrus development and haven't used it in about 5 years, so can't answer your question. Roland Huss and Marcel May have not been involved with the project for several years, eitber, AFAIK.

**Comment by svettwer** [comment]
Hiho!

Unfortunately I'm a little bit short on time.

>How to put wait after microservice API call for angular application?

You already put a wait to the application. I assume that the problem lays in the configuration.

You wrote:
>I am using java DSL, website is built with angular 7, On click of search I get search result but above samples don't wait for result data which is dynamically loaded.

So I assume the Element `search-results` is visible directly after the page has been loaded, right? Therefore the condition is met and the test continues. You could change the `waitUntil` condition to check for some classes or IDs in the dynamically loaded content.

BR,
Sven

**Comment by vmasule** [comment]
I appreciate your time @svettwer.

`search-results ` is visible when I click on a button(API call behind) that brings result back then result gets loaded in page dynamically.  

Problem is API response takes 10 - 15 Seconds i.e `search-result` takes that much time to load. I have even tried putting `.timeout(15000L)` but still I am getting below error.

```
com.consol.citrus.exceptions.TestCaseFailedException: no such element: Unable to locate element: {"method":"class name","selector":"search-results"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
```

> I assume that the problem lays in the configuration.

I am using same configuration as mentioned in sample `citrus-java-sample-selenium` project provided by Citrus.

**Comment by vmasule** [comment]
hi,  @svettwer your update on this will be highly appreciated.

**Comment by svettwer** [comment]
Hi @vmasule.

As mentioned, I'm currently short on time and will respond as soon as possible. 

BR, 
Sven

**Comment by svettwer** [comment]
Hi!

From my perspective, this should work as expected. You setup a appropriate timeout for the result to be loaded and selenium will care for the rest.

Nevertheless, I'm a little confused. As you opened the issue, you wrote:
>On click of search I get search result but above samples don't wait for result data which is dynamically loaded.

but now you say:
>Problem is API response takes 10 - 15 Seconds i.e search-result takes that much time to load. I have even tried putting .timeout(15000L) but still I am getting below error.

So did you receive the error message the whole time or appeared it as you increased the timeout?

If the request takes that long, increasing the wait a little bit further might help you out. As a background information: Citrus does not apply any custom wait operations but just reuses the selenium API. Therefore it's likely one of these typical wait issues with selenium.

For me, it's pretty tough to reproduce the issue as I have no system that behaves like yours. Would it be possible for you to create a sample test case or project that makes your issue reproducible? Otherwise, I'm afraid i can't help you out.

BR,
Sven

**Comment by svettwer** [comment]
Closed due to inactivity
