### ISSUE TITLE
JmsTopicSubscriber swallows exceptions when failed to wait for topic subscriber to start subscription

### ISSUE THREAD

**Issue by AliaksandrHaurylau** [citrusframework/citrus#677]
Citrus Version = 2.7.6, 2.8.0
Expected behavior: Exception thrown and can be handled by test runner, test is red

Actual behavior: Exception just logged as warning, but not re-thrown and, therefore, not handled by test runner, test might be green or fail after by indirect reasons

I suppose, following source fragment is responsible for this:

https://github.com/citrusframework/citrus/blob/master/modules/citrus-jms/src/main/java/com/consol/citrus/jms/endpoint/JmsTopicSubscriber.java
```
 public void start() {
        subscription.execute(this);
        try {
            if (started.get()) {
                log.info("Started JMS topic subscription");
            }
        } catch (InterruptedException | ExecutionException e) {
            log.warn("Failed to wait for topic subscriber to start subscription", e);
        }
    }
```
I'm afraid, I'm unable to provide steps for reproduce it as subscription issue on activeMQ is other thing, but, code fragment is obvious enough. Sorry if I'm wrong

**Comment by svettwer** [comment]
Hi!

So based on that code, tests which assert certain actions on a JMS Topic will not turn green because of that. As the subscription has not been established, Citrus would not be able to receive any messages from a JMS Topic or push any messages from a JMS Topic. Therefore test cases performing JMS Topic actions would fail during the test case execution. So we are safe from false positives here.

I am currently not sure what led to this issue. Did you experience any false positives with JMS-Topics or did you just explore the JMS Module, found that part of the code and thought this might be an issue?

BR,
Sven

**Comment by AliaksandrHaurylau** [comment]
Hi, thank for the response
We're having a SUT as a stack of microservices  and ActimeMQ is one of them, it may be unreachable among the others. So, any exceptions likely to be useful and should be thrown. I'm not sure why we got false-positive tests, but they were, indeed. Maybe, it connected with Citrus reporting, I have to recheck.
WBR, Alex

**Comment by svettwer** [comment]
Hi,

the JMS Module of Citrus is one of the most widely used. From my experience false positives or flaky tests are a most likely a result of using Citrus in a wrong way somehow. But in case you found a scenario where a false positive is reproducible, we would be glad to have a look.

BR,
Sven

**Comment by svettwer** [comment]
Closed due to inactivity
