### ISSUE TITLE
WaitConditionBuilder constructor never sets the condition in the builder despite taking it as an argument

### ISSUE THREAD

**Issue by he-ritter** [citrusframework/citrus#861]
**Citrus Version**
3.2.1

**Expected behavior**
The constructor should set the condition in the underlying builder.

**Actual behavior**
The constructor does not set the condition in the underlying builder, it has to be set manually.

**Test case sample**
```
Wait.Builder builder = new Wait.Builder()
        .time(timeout);
WaitActionConditionBuilder waitActionConditionBuilder = new WaitActionConditionBuilder(condition, builder);
```
does not work. The ```condition``` will never actually be set. Instead,
```
Wait.Builder builder = new Wait.Builder()
        .time(timeout)
        .condition(condition);

WaitActionConditionBuilder waitActionConditionBuilder = new WaitActionConditionBuilder(condition, waitBuilder);
```
has to be performed. This makes the argument ```condition``` in the ```WaitActionConditionBuilder``` useless.
I'd propose to add a line ```builder.condition(condition)``` in the constructor of ```WaitConditionBuilder```.

**Comment by bbortt** [comment]
@he-ritter sounds good to me, thanks for reporting. would you be able to submit a PR?

**Comment by bbortt** [comment]
@akuz0 just follow the steps proposed. make the constructor argument meaningful. test it using the code proposed ("assert condition is applied in constructor").

**Comment by bbortt** [comment]
what about following the `super(condition, builder)`.. you'll end up in the [`abstract class WaitConditionBuilder`](https://github.com/citrusframework/citrus/blob/c1e3299fe1b5ba46ec62fd2c22cdd2e859ecacbe/core/citrus-base/src/main/java/com/consol/citrus/container/WaitConditionBuilder.java#L46). there you could touch the builder - once. e.g.:
```shell
$ git diff
diff --git a/core/citrus-base/src/main/java/com/consol/citrus/container/WaitConditionBuilder.java b/core/citrus-base/src/main/java/com/consol/citrus/container/WaitConditionBuilder.java
index c6e498cbb..c94bb5321 100644
--- a/core/citrus-base/src/main/java/com/consol/citrus/container/WaitConditionBuilder.java
+++ b/core/citrus-base/src/main/java/com/consol/citrus/container/WaitConditionBuilder.java
@@ -43,7 +43,7 @@ public abstract class WaitConditionBuilder<T extends Condition, S extends WaitCo
      */
     public WaitConditionBuilder(T condition, Wait.Builder builder) {
         this.condition = condition;
-        this.builder = builder;
+        this.builder = builder.condition(condition);

         this.self = (S) this;
     }
```

**Comment by bbortt** [comment]
well, that certainly could be a problem. on the other hand, I would expect such a constructor to enforce its condition, because it is kinda "a command from a higher rank".
however, I agree on that: the proposed solution does not fully satisfy.
I can think of two different ways of addressing it:
* add another constructor, with just the builder. it is more obvious, that the other constructor will override the condition.
* introduce "a rule" e.g.
  * use condition if builder has none yet
  * if builder already has a condition, do nothing
anyhow, it is for sure important to document the implementation. @christophd any thoughts on this?

**Comment by bbortt** [comment]
deprecate, but not remove. this would be breaking. then open an issue to remove it and add it to the citrus 4.0 project.

**Comment by christophd** [comment]
I have had a closer look and yes the constructor arguments are not very intuitive. It is assumed that the condition is set manually on the builder before using the constructor.

I think the intention was to let the user use the DSL methods for building the action rather than using the constructors directly. Something like

```
waitFor()
  .execution()
  .action(new FooAction())
  .time(timeout)
```

Also when setting a custom condition like this:

```
waitFor()
  .condition(new MyCondition())
  .time(timeout)
```

With that the constructor arguments are handled internally. Yet we can improve the constructor arguments as described in this issue.

**Comment by christophd** [comment]
@bbortt @akuz0 please have a look #875
