### ISSUE TITLE
new `DefaultTestLoader` does not support default arguments

### ISSUE THREAD

**Issue by bbortt** [citrusframework/citrus#885]
@christophd the new [`DefaultTestLoader`](https://github.com/citrusframework/citrus/blob/main/core/citrus-base/src/main/java/com/consol/citrus/common/DefaultTestLoader.java) has just an empty constructor. the old one (`XmlTestLoader`) [had some arguments to it](https://github.com/citrusframework/citrus/blob/v3.2.1/core/citrus-spring/src/main/java/com/consol/citrus/common/XmlTestLoader.java#L59).

should I add a second constructor or would you prefer a builder pattern?

e.g.

```java
    public DefaultTestLoader() {
        // Standard constructor
    }

    public DefaultTestLoader(Class<?> testClass, String testName, String packageName, CitrusContext citrusContext) {
        this.testClass = testClass;
        this.testName = testName;
        this.packageName = packageName;
        this.citrusContext = citrusContext;
    }
```

or

```java
    public DefaultTestLoader [with]TestClass(Class<?> testClass) {
        this.testClass = testClass;
        return this;
    }

    // etc...
```

I am unsure, which one does look nicer? or should I add both?

**Comment by bbortt** [comment]
also `load` did return the `TestCase` in the past. a new method `loadAndGetTestCase` could do that (combination of `load` and `getTestCase`). that would allow as to do everything in a one-liner (as the old implementation did).

**Comment by christophd** [comment]
So the thing with load returning the `TestCase` is that the loader will create and run the test case now. Before the loader did just create the test case and the caller had the responsibility to run the test afterwards. I changed this so the loader will create and run the test case because XML, Groovy and other test loaders should behave the same way.

Also the way it has been implemented before the Groovy test was run actually before the test enters the execution phase (from a reporting point of view).

Now the loader loads the test and runs the test so the test case that would be returned by load method is finished already.  Instead of returning the test case with the load method the loader provides hooks that users may use to add functionality to the test once it has been created. This way you may adjust the test before/after it has been started.

**Comment by bbortt** [comment]
@christophd that does make sense and my final solution in #886 is completly in sync with that. I also found a bug in the initialization which is fixed in this PR.

**Comment by bbortt** [comment]
@christophd this still hasn't been released. can we have one more bugfix release (`v3.3.1`) in "the old year"? ;)

**Comment by christophd** [comment]
@bbortt yes, sorry for the delay. I am planning it for the end of this week. Ok for you?
